<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config["live"] = ENVIRONMENT!="development";
$config["admin_panels"] = array( "admin" );
$config["site-name"] = "Website Name";
$config["club-type"] = "Rotary";
$config["address"] = "ADDRESS";
$config["phone"] = "PHONE NUMBER";
$config["meetings"] = "Mon - Fri, 08:00 - 16:00";
$config["site-email"] = "CONTACT EMAIL";
$config["no-reply"] = "SYSTEM EMAIL";
$config["year-founded"] = "YYYY";
$config["facebook"] = "https://facebook.com/facebook";
$config["twitter"] = "twitter-handle";
$config["twitter-widget-id"] = "";
$config["youtube"] = "";
$config["instagram"] = "";
$config["linkedin"] = "";
$config["general"] = "1";
$config["author"] = "BIT Technologies";
$config["author-url"] = "http://www.bittechnologyz.com";
$config["images_size_definitions"] = [ "xs"=>"Extra Small", "sm"=>"Small", "md"=>"Medium", "lg"=>"Large", "xl"=>"Extra Large" ];
$config['enable_profiler'] = false;