<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config["live"] = ENVIRONMENT!="development";
$config["admin_panels"] = array( "admin" );
$config["site-name"] = "S.A.H.T.C - The Hospitality School";
$config["club-type"] = "Default";
$config["address"] = "32 Arcturus Road, Highlands, Harare";
$config["phone"] = "0777147927";
$config["meetings"] = "Mon - Fri, 08:00 - 16:00";
$config["site-email"] = "info@sahtc.com";
$config["no-reply"] = "no-reply@dblprime.com";
$config["year-founded"] = "2019";
$config["facebook"] = "https://facebook.com/";
$config["twitter"] = "dblprime";
$config["twitter-widget-id"] = "";
$config["youtube"] = "";
$config["instagram"] = "";
$config["linkedin"] = "";
$config["general"] = "1";
$config["author"] = "BIT Technologies";
$config["author-url"] = "http://www.bittechnologyz.com";
$config["images_size_definitions"] = [ "xs"=>"Extra Small", "sm"=>"Small", "md"=>"Medium", "lg"=>"Large", "xl"=>"Extra Large" ];
$config['enable_profiler'] = false;